### ISSUE TITLE
Error in seq.int(cutpoints[1] + 1, cutpoints[2] - 1) :    'from' must be a finite number... when using StataMP 15 on OS X

### ISSUE THREAD

**Issue by praxis87** [lbraglia/RStata#11]
As mentioned in the title, I get the "Error in seq.int(cutpoints[1] + 1, cutpoints[2] - 1) :  'from' must be a finite number" message . I looked up the previous issue and noticed the "set more off, permanently" solution, but didn't work.

It seems that R succeeded in calling Stata and running RStata.do in stata. I looked at the stata log file, which showed something like this...

. do RStata.do 

. set more off

. 
. capture noisily {
. /*RSTATA: cut me here*/
. display 3*5
15
. /*RSTATA: cut me here*/
. } /* end capture noisily */

. exit, clear STATA

I suspect that the error has to do with capturing stata output and reading into R.

Any suggestion would be greatly helpful. Thanks.

**Comment by praxis87** [comment]
Oh well. I figured it out, I guess. 

I guess that the problem was in my .Rprofile option setting. Here's my original one that caused the error above

"
library(RStata)

options("RStata.StataPath" = "/Applications/Stata/StataMP.app/Contents/MacOS/StataMP")

options("RStata.StataVersion" = 15)
"

I changed it into

"
library(RStata)

options("RStata.StataPath" = "/Applications/Stata/StataMP.app/Contents/MacOS/stata-mp")

options("RStata.StataVersion" = 15)
"

The error message disappeared when I changed "StataMP" into "stata-mp". I suppose StataMP call for GUI interface version of Stata while stata-mp terminal version, which resolve the problem.

anyways... Sorry for the noise that I made here and thanks a lot for sharing this awesome product.

Best,

Jinseok

**Comment by lbraglia** [comment]
ok, best, Luca

**Comment by hbahamonde** [comment]
Hey, I am using Stata IC 15, and found the same problem. Following @praxis87 comment, I tried,

`options("RStata.StataPath" = "/Applications/Stata/StataMP.app/Contents/MacOS/stata-ic")`

but it didn't work. Any word of wisdom? Thanks!

**Comment by biancamanago** [comment]
@hbahamonde I think your issue is that you still have StataMP in there

Try changing it to:

`options("RStata.StataPath" = "/Applications/Stata/StataIC.app/Contents/MacOS/stata-ic")`
