### ISSUE TITLE
Plotting graphs with Rstata

### ISSUE THREAD

**Issue by jennykathambi90** [lbraglia/RStata#21]
Dear Team,

I am trying to plot a graph with rstata but nothing is showing. Kindly help.

**Comment by lbraglia** [comment]
Save the plot to a file; think you're using Stata not in an interactive way but from batch/do file.

**Comment by jennykathambi90** [comment]
> Save the plot to a file; think you're using Stata not in an interactive way but from batch/do file.

Dear @lbraglia do you mind sharing a script on how to export the image to a file? This is because I am new to stata in general. Thank you.

**Comment by lbraglia** [comment]
Sorry this is not the proper place (it's a bug tracking system for an R package), and being a long time i do not use Stata for plotting I don't remember: you can ask for help on google or stackoverflow instead... And btw probably you'd better getting acquainted with Stata itself before using RStata :) best regards, Luca
